server:
  port: 8082

spring:
  application:
    name: 'mail'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

mail:
  transport:
    protocol: smtp
  smtp:
    auth: true
    starttls:
      enable: true
  debug: true