server:
  port: 8080

spring:
  application:
    name: 'upwork'
  datasource:
    username: root
    url: 'jdbc:mysql://192.168.1.100:3306/db_upwork'
    password: 'time60243112'
  jpa:
    properties:
      hibernate:
#        format_sql: true
    hibernate:
      ddl-auto: 'update'


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
